---
title: "Oppbevaring av sykt matriale"
description: |
  Hmmmmm.   
author:
  - name: Lyder Aleksander Mathisen 
    url: https://onelyder.com/about
    affiliation: Me, Myself, and I
    affiliation_url: https://onelyder.com
date: 10-21-2021
creative_commons: CC BY-NC
output:
  distill::distill_article:
    css: hospital_header.css
    self_contained: false
#preview: simon-sjakk.jpg
categories:
  - R
  - R-studio
  - Referanser
  - Fag
---

# R-code & Packages

In this section I will storage material useful for R-studio and R-code.
References will be somewhat related to R, but mainly will these links be
brought about academic writing, workflow and project management. It
also const of Github users, thereabout frameworks and rich content
regarding *modelling, time series, data* and *analysis.*

<!--# break -->

-   **`miltonfmr`** (*quant-site*)

    -   <https://miltonfmr.com/complete-list-of-libraries-packages-and-resources-for-quants/>



-   **`Time-series`**

    -   <http://www.time-series.net/>

    -   Found this when I serched for material regarding VAR. Think I
        first found this link:<http://www.fsb.miamioh.edu/lij14/> and
        this time-series via that. It should be a lot of example and
        framework relatied things regarding R-code, finance, but also
        academic list and material…

    -   Code
        <https://sites.google.com/view/davidgabauer/econometric-code>

    -   Github: <https://github.com/GabauerDavid/ConnectednessApproach>

    -   R-workbooks:
        <https://sites.google.com/view/davidgabauer/use-rpython>

        **Notes:** I have testet some of the source files and scripts,
        and it looks very nice! I finally have found a script that
        cointains functions and setups necesssary for forcasting
        matrix\`s over differant time-periods. I have stored the files
        on my mac-PC. `ConnectednessApproach-master` & `firefox_files` &
        `dy2012_copi` are foldes containing source code on my desktop.
        
    

- **`ropensci`**

   -  <https://ropensci.org>
   - Data, software & reproducibility
       


<!--# break -->


<!--# break -->

## Packages, functions & librarys available in R

<!--# break -->

Here I will store packages I personally find usefull. These packages
will in general relate to datasience, finance and time seres modelling.
But also r-markdown and *reproducable reaserch document* packages.

**Material**



<!--# break -->

## R-Markdown & Reproducable Reasearch

-    **Ulyngs** (*oxford template*)

    -   <https://github.com/ulyngs/oxforddown>

-    **NTNU Latex og stil** 

     - https://github.com/COPCSE-NTNU/master-theses-NTNU/tree/master/ntnuthesis 
     - https://www.math.ntnu.no/emner/TMA4268/2018v/1Intro/


-   **`rstudioapi`**

    - https://cran.r-project.org/web/packages/rstudioapi/rstudioapi.pdf
    - brukes feks til theme edit

-   **`formatr`**

    -   <https://yihui.org/formatr/#2-reformat-r-code>

-   **`Bookdown`**

    -   <https://bookdown.org/>

    -   <https://www.r-bloggers.com/2018/08/how-to-self-publish-a-book-customizing-bookdown/>

    -   <https://bookdown.org/> (alle bøkene)
    

  <!--# break -->

-   **RiffomonasProject**

    -   -   Youtube-Bruker: `RiffomonasProject`
            <https://www.youtube.com/c/RiffomonasProject>

<!--# break -->

## Data Wrangeling

-   **`tidyverse`** (*General Package for Data Sience*)

    -   book: <https://r4ds.had.co.nz/>

    -   `dplyr`

    -   `readr`

    -   `lubridate` (*time, dateobject*)

        -   Overview of packages <https://www.tidyverse.org/packages/>

-   **NickCHK**

    -   -   Youtube-Bruker: `NickCHK`

    -   -   R-Hubs: <https://rpubs.com/NickCHK/>

<!-- -->

## Statistical/Econometric models 
(*empirical oriented*)

-   **`MTS`** (*VAR framework*)

    -   Tsay, R. S
    -   <https://github.com/d-/MTS/blob/master/R/MTS.R>
    -   book: Tsay, R. S. (2014). An Introduction to Analysis of
        Financial Data with R. John Wiley & Sons.
    -   Tsay, R. S. (2013). Multivariate Time Series Analysis: With R
        and Financial Applications. John Wiley & Sons.

-   **`NTS`** (*Nonlinear Time Series Analysis*)
    
    - Tsay, R. S
    - <https://faculty.chicagobooth.edu/ruey-s-tsay/research/nonlinear-time-series-analysis>

-   **Prof. Daniel P. Palomar** (*VAR/ARMA Vingette*)
    
    - <https://palomar.home.ece.ust.hk/MAFS6010R_lectures/Rsession_time_series_modeling.html>
    - <https://cran.r-project.org/web/packages/portfolioBacktest/vignettes/PortfolioBacktest.html>






<!--# break -->

## Finance, Risk, Timeseries, Optimization functions

-   **`Finance View Cran`**

    - All finance-related packages on R (CRAN). Amazing.

    - <https://cran.r-project.org/web/views/Finance.html>
    
-   **`introcompfinr`**
    
    - [Link Introcompfin](https://bookdown.org/compfinezbook/introcompfinr/Determining-Mean-Variance-Effici.html)

-   **`Rmetrics`** (*Framwork, several packages published*)

    -   PDF-book Portfolio Optim:
        <https://www.rmetrics.org/downloads/9783906041018-fPortfolio.pdf>
    -  Rmetrics fPortfolio vignette(GOOD) part 1 & 2:    
        - P1: <https://miltonfmr.com/the-complete-guide-to-portfolio-optimization-in-r-part1/#rollstats>
        - P2: <https://miltonfmr.com/the-complete-guide-to-portfolio-optimization-in-r-part2/>

-   **`tidyquant`** (*Finance*)

    -   link: <https://business-science.github.io/tidyquant/>

<!--# break -->

-   **`BLCOP`** (*Black-Litterman model framework*)

    -   link:
        <https://cran.r-project.org/web/packages/BLCOP/vignettes/BLCOP.html>
    -   install: install.packages(“BLCOP”,
        repos=“<http://R-Forge.R-project.org>”)
    -   Found via: <https://r-forge.r-project.org/R/?group_id=156>
    
    
    
    
-   **`QRMtools`**(*general functions finance*)

    
    - I found this on youtube sometime when I studied for my exams. I have stored the link ever since, very nice and powerful tools and knowledge sharing!
    - <https://cran.r-project.org/web/packages/qrmtools/vignettes/geometric_risk_measures.html>
    - <https://www.qrmtutorial.org/r-code?fbclid=IwAR1Qnkkq9d_Gt28-ptQmTmLpbIcGNwMudKxYyKFONKgkfWoa8X8p1HIXLg4>
<!--# break -->

-   **`FRAPO`**

    -   <https://www.pfaffikus.de/books/jwex2/>
    -   <https://www.pfaffikus.de/>

<!--# break -->

## Blogroll: Finance & R-code

 Found this link via rgarch packages site on CRAN:
 <http://www.unstarched.net/> via this link I found this link <http://www.unstarched.net/blog/>
 and violah: I came here <https://www.portfolioprobe.com/2012/01/05/the-top-7-portfolio-optimization-problems/>
 which gave me this **blogroll** <https://www.thertrader.com/> with a nice vignette: <https://www.thertrader.com/2017/06/04/linking-r-to-iqfeed-with-the-quanttools-package/>
 
 This is a good example of how quick, but also contentrich, the *R-community*, and especially for *finance* are!! There are so much interessting content, most likley written by the smartest/best people, availible for free! This happends all the time when I am searching around looking for packages, functions or methods I can use for my own project. I end up reading or studiung cases/ functions that is not actuelly what I am suposed to do... The only downside about R, is that you probebrly are going to burn out much of your planned *work* hours. 
 So stay orginzed, but also; *take some time enjoying what`s out there*!! I am feeling blessed, really.
 
 **BLOG-ROLL**
 
 
 -   **`The R Trader `**
 
 link: <https://www.thertrader.com/>
  
 -   **`r-bloggers`**
 
 link: <https://www.r-bloggers.com/>
 
 -   **`datacamp.`**
 
 link: <https://learn.datacamp.com/>
  




# Generelle Notes

In this section I indtend writing down my own personal "studing" notes, and make space for chapters/parts for themes I find interessting writing notes aboout. These notes are written during a typical working sesh, or just another day I find it interessting searcing around the AMAZING community for datasience resoruces! 

My notes could be anything within the category of *datasience*, *modelling*, *finance* and escpacially *R*. I want to gather my notes in one place(folder), in the hope of possible utizlizing a connection I suspect may excist between themes I learn about during my work sessions.
Said in another way; *You may find random themes and paragraphs here.* 

## File types, how to store them and key differences

It dosent matter what kind of analyst you are trust me. R, Python, Java, C, C++, S or wathever; file-types and folderstructure is key if you want to master, or just even use code and programming-languages efficient. As a result of that, I indtend storing my own personal notes from studiong/resarching about filetypes I have often met when I have coded/worked on my own personal prosjects. 

I have felt both the frustration and the irritation of not understanding/taking enough time understanding what Its really all about. As a matter of fact, If you dont understand how the algoritm likes he`s food served.. you actuelly deserve beeing tortured by error messages. At least coused from not handling your files proper. It may sound wierd, but it could exist a kind of relashionship between algortims and humans in the sens of treting whats deare in the proper way. File and data is the maintance for the script!!! 

Below I write down extention-names on filetypes I recollect on the go. If the [] box is emtpty, it means I have not started researching properly yet. 

<!--# break -->
_______________________________________________________________________________

**CSV**[x]    **XLS**[x]    **zip**[]    **gz**[]   **tsv**[]    **txt**[]
==============================================================================
<!--# break -->

- *CSV* -> stores the data as *text*. Can only store the values, not formatting and formulas etc. 
<!--# break -->
- *XLS* -> stores data *binary file*. Readable for the computer. Can store values, formatting......

<!--# break -->

**MATERIAL FEEDER**

Here I will "feed" the block with links, notes, refs and material I explore. These need to be placed in the right sections. This part is then not included in the official "document" and will be removed when there`s eventuelly no more links to feed. I have placed this feed-block on the top of the document so I can easily see it, and start sortering when i begin a work section. 

<file:///C:/Users/lyder/Desktop/Bibliography-/Notes/bookmarks_7_15_21.html>

**ORGANISER DETTE!**

```  
## Linker
https://libraries.io/cran/RefManageR

https://books.ropensci.org/drake/index.html

https://www.youtube.com/watch?v=jU1Zv21GvT4&t=4055s

https://www.rstudio.com/resources/rstudioglobal-2021/maintaining-the-house-the-tidyverse-built/
  
https://docutils.sourceforge.io/docs/ref/doctree.html#image

https://books.ropensci.org/drake/index.html

  
  
## PDF
R-litteratur: mappe skrivebordet!!

Har også sett på apperence_themes: shiny. 

```

# Intro (START)

This document contains notes, links, referances and matarial I have used
throughout the prosses.



<!--# break -->



<!--# break -->


<!--# break -->



<!--# break -->

## Refs to my own work stored *some_where*

-   **Output github “test”**
    <https://github.com/lyder7/thesis-rasp/blob/master/r-markdown/test-html/test.md>

    -   Denne har bilder, og formattering slik som html versjonen hadde.
        Fant denne linken via *thesis-rasp*

-   **Resultater lagret i txt dokument**
    <https://github.com/lyder7/thesis-rasp/blob/master/r-markdown/test-html/resultater.txt>

-   **test.Rmd**
    <https://github.com/lyder7/thesis-rasp/blob/master/r-markdown/test-html/test.Rmd>

-   **generelt lagret**
    <https://github.com/lyder7/thesis-rasp/tree/master/tekst>

    <!--# break -->