---
title: "About this site"
description: |
  Personal Portfolio Web Page hosted with my domain @onelyder
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```



## English about me  

My Professional competence are mainly within the academic finance- and economy literature and science. Based upon this knowledge, I have build serious experience, competence and knowledge within the field of Data Science. I personally believe combining these two disciplines are very natural believe they share key common elements.

I daily use code and various programming languages solving mainly analytically problems or/and project-assignments. Some of the langues i commonly use are: `R` & `Python.` (*R = Preferred Language*).  

Based on the code-syntax knowledge I also master text- and document formatting languages/tools such as `Rmarkdown`, `Latex`, `Pandoc`, `HTML` and `Markdown.` Any type of output-format for the final-project report are within my “competence tool-box”, and I really understand the importance of generating the optimal- and a professional looking report.

I use `GitHub` (terminal git bash) for project admin and version control. Folder structure and working directory are elements I think are essential. I can deliver the same quality and results working on a Windows computer or a Mac. I know how to optimize the workflow on both operating systems.

Please contact me if you want to see any former work and material I have been a part of from my personal portfolio. I would be happy to share it with you and get valuable feedback and perspectives.
