---
title: "Referanser til syke ting"
author:
  - name: Lyder Aleksander Mathisen
date: 10-21-2021
output:
  distill::distill_article:
    toc_depth: 3
    toc_float: true
---

# myweblibrary 4later

## Linux Tools

### Docker

-   Et program som gjør det mulig å bruke- hente ande enviorments
    relatert til prosjektet du jobber med.
-   Du kan fra terminalen laste inn IMAGES som består av filer, mappper
    og alt du trenger for å kunne jobbe med alt du trenger af
    funksjoner, pakker og anre sting rundt prosjektet som er nødvendig.
    . Det har likhetstrekk med det som kalles "`Viritual Machines`".
-   Vi kjører økte i et området som består kun v

## Terminal Linux Bash

## Cmd-line tools

-   [Bash Reference
    Manual](https://www.gnu.org/software/bash/manual/bash.html#Basic-Shell-Features)

-   [Bash Manual
    Pages](http://linuxcommand.org/lc3_man_page_index.php#shell){.uri}

-   [Codingblocks Resources](https://www.codingblocks.net/resources/)

-   [brew](https://brew.sh/){.uri} (mac)

## Podcasts - Coding/Programming

-   [DEV Community Podcasts](https://dev.to/pod)

    -   Består av alle mulige podcaster relatert til programmering, kode
        og development.
    -   Anbefales å lage egen bruker, og bruke de andre
        community-ressurser tilgjengelige
    -   Gir generelt en fin portal inn til "community", og gir deg
        tilgang til veriert info og nyheter om ulike områder.
    -   [Link til DEV](https://dev.to/)

-   **Coder Radio**

-   **Lex Fridman Podcast**

-   **Command-line Heroes**

-   Redhat radio

-   **syntax**

-   **r-weekly**

-   **Shiny developer Series**

## R in General

-   [HADLEY WICKHAM NETT
    SIDE](http://hadley.nz/ "Founder tidyverse package"){.uri}

-   [rweekly](https://rweekly.org/){.uri}

-   [rladies](https://rladies.org/)

-   [shinydevseries.com](https://shinydevseries.com/){.uri}

-   [unleash-shiny.rinterface.com](https://unleash-shiny.rinterface.com/web-dependencies.html "book"){.uri}

-   [https://](https://peertube.linuxrocks.online/videos/trending){.uri}[peertube.linuxrocks](https://peertube.linuxrocks.online/videos/trending "web linux tv"){.uri}[.online/videos/trending](https://peertube.linuxrocks.online/videos/trending){.uri}

-   [emilhvitfeldt.com](https://www.emilhvitfeldt.com "blog"){.uri}

### Web

-   [Destill Github Guide](https://github.com/jhelvy/distillery){.uri}

-   <https://distillery.rbind.io/>

-   <https://www.jhelvy.com/>

    -   ^[Denne Githuben er sykt bra!]{.smallcaps}^

-   <https://ellakaye.github.io/distilltools/>

-   <https://github.com/seankross/postcards>

-   [Hugo Web Page](https://gohugo.io/hugo-modules/use-modules/)

-   [ep](https://epirhandbook.com/en/index.html)[irhandbook R
    bok](https://epirhandbook.com/en/index.html "bok")

    -   ^[Legendarisk bok om alt rundt R kode]{.smallcaps}^

-   [useR!](https://user2021.r-project.org/){.uri}

-   [Rstudio Cloud](https://rstudio.cloud/, "Rstudio Cloud"){.uri}

### Pakker

-   `here`

-   `fs`

-   `diagrammR`

-   `Tidyverse`

-   `devtools`

-   `pacman`

-   `remotes`

-   `renv`

-   `rmarkdown`

-   `Word`

-   `reportfactory # auto-organization of R Markdown outputs`

-   `officer # Powerpoints, and HTML files`

### Data Manipulasjon /Formatting

-   `dplyr`

-   `margitrr`

-   `pacman`

-   rlang

-   `lubridate`

-   `stringr`

-   `purrr`

-   `tidyr`

-   `readr`

-   `readxl`

-   `opsenxlsx`

-   `vroom`

-   `tidyxl`

-   `rio`

-   `janitor`

### rmarkdown i R:

-   `bookdown`

-   `blogdown`

-   `rmarkdown`

-   `knitr`

##### **Andre rapport/nettside relaterte pakker**

-   `bs4 bootstrap theme bslib themes`

-   `reprex  downlit  themes destill/`

-   `rmkardown`

-   `web tidytex  latex pack`

-   `for R articls  article templates`

-   `rmarkdown`

-   `postcards themes`

-   `destill convert an R Markdown script into a dashboard`

-   `shiny`

-   `felxeboard`

    ### 

### web/html-output helpers:

-   `jsonlite`

### workflow i R:

-   `targets`

-   `drake`

### API

-   `plumbr`

-   `rlang?`

<!-- -->

-   **`miltonfmr`**`(quant-site)`

    -   [\<https://miltonfmr.com/complete-list-of-libraries-packages-and-resources-for-quants/>](https://miltonfmr.com/complete-list-of-libraries-packages-and-resources-for-quants/){.uri}

-   **`Time-series`**

    -   [\<http://www.time-series.net/>](http://www.time-series.net/){.uri}

    -   Found this when I serched for material regarding VAR. Think I
        first found this
        link:[\<http://www.fsb.miamioh.edu/lij14/>](http://www.fsb.miamioh.edu/lij14/){.uri}
        and this time-series via that. It should be a lot of example and
        framework relatied things regarding R-code, finance, but also
        academic list and material...

    -   Code
        [\<https://sites.google.com/view/davidgabauer/econometric-code>](https://sites.google.com/view/davidgabauer/econometric-code){.uri}

    -   Github:
        [\<https://github.com/GabauerDavid/ConnectednessApproach>](https://github.com/GabauerDavid/ConnectednessApproach){.uri}

    -   R-workbooks:
        [\<https://sites.google.com/view/davidgabauer/use-rpython>](https://sites.google.com/view/davidgabauer/use-rpython){.uri}



-   **`ropensci`**

    -   [\<https://ropensci.org>](https://ropensci.org){.uri}
    -   Data, software & reproducibility

# [R-code & Packages]{.ul}

<!--# break -->

-   **`miltonfmr`** (*quant-site*)

    -   <https://miltonfmr.com/complete-list-of-libraries-packages-and-resources-for-quants/>

-   **`Time-series`**

    -   <http://www.time-series.net/>

    -   Found this when I serched for material regarding VAR. Think I
        first found this link:<http://www.fsb.miamioh.edu/lij14/> and
        this time-series via that. It should be a lot of example and
        framework relatied things regarding R-code, finance, but also
        academic list and material...

    -   Code
        <https://sites.google.com/view/davidgabauer/econometric-code>

    -   Github: <https://github.com/GabauerDavid/ConnectednessApproach>

    -   R-workbooks:
        <https://sites.google.com/view/davidgabauer/use-rpython>


-   **`ropensci`**

    -   <https://ropensci.org>
    -   Data, software & reproducibility

-   Packages, functions & librarys available in R

    <!--# break -->


    **Material**

    <!--# break -->

    ## R-Markdown & Reproducable Reasearch

    -   **Ulyngs** (*oxford template*)

    <!-- -->

        -   https://github.com/ulyngs/oxforddown

    -   **NTNU Latex og stil**

        -   [\<https://github.com/COPCSE-NTNU/master-theses-NTNU/tree/master/ntnuthesis>](https://github.com/COPCSE-NTNU/master-theses-NTNU/tree/master/ntnuthesis){.uri}
        -   [\<https://www.math.ntnu.no/emner/TMA4268/2018v/1Intro/>](https://www.math.ntnu.no/emner/TMA4268/2018v/1Intro/){.uri}

    -   **`rstudioapi`**

        -   [\[http\](https://cran.r-project.org/web/packages/rstudioapi/rstudioapi.pdf)rstuio
            link
            resdtudioPAI](https://cran.r-project.org/web/packages/rstudioapi/rstudioapi.pdf){.uri}
        -   brukes feks til theme edit

    -   **`formatr`**

        -   [format reckde
            tools](https://yihui.org/formatr/#2-reformat-r-code){.uri}

    -   **`Bookdown`**

        -   [\<https://bookdown.org/>](https://bookdown.org/){.uri}

        -   [\<https://www.r-bloggers.com/2018/08/how-to-self-publish-a-book-customizing-bookdown/>](https://www.r-bloggers.com/2018/08/how-to-self-publish-a-book-customizing-bookdown/){.uri}

        -   [\<https://bookdown.org/>](https://bookdown.org/){.uri}
            (alle bøkene)

    <!--# break -->

    -   **`RiffomonasProject`**

        -   Youtube-Bruker: `RiffomonasProject`
            [\<https://www.youtube.com/c/RiffomonasProject>](https://www.youtube.com/c/RiffomonasProject){.uri}

    <!--# break -->

<!--# break -->

<!--# break -->

## Data Wrangeling

-   **`tidyverse`** (*General Package for Data Sience*)

    -   book: <https://r4ds.had.co.nz/>

    -   `dplyr`

    -   `readr`

    -   `lubridate` (*time, dateobject*)

        -   *Overview of packages* <https://www.tidyverse.org/packages/>

-   **`NickCHK`**

    -   Youtube-Bruker: `NickCHK`

    -   R-Hubs: <https://rpubs.com/NickCHK/>

<!-- -->

## Statistical/Econometric models

(*empirical oriented*)

-   **`MTS`** (*VAR framework*)

    -   Tsay, R. S
    -   <https://github.com/d-/MTS/blob/master/R/MTS.R>
    -   book: Tsay, R. S. (2014). An Introduction to Analysis of
        Financial Data with R. John Wiley & Sons.
    -   Tsay, R. S. (2013). Multivariate Time Series Analysis: With R
        and Financial Applications. John Wiley & Sons.

-   **`NTS`** (*Nonlinear Time Series Analysis*)

    -   *Tsay, R. S*
    -   <https://faculty.chicagobooth.edu/ruey-s-tsay/research/nonlinear-time-series-analysis>

-   **Prof.
    Daniel P.**[home.ece.ust.hk/MAFS6010R_lectures/Rsession_time_series_modeling.html](https://palomar.home.ece.ust.hk/MAFS6010R_lectures/Rsession_time_series_modeling.html){.uri}

    -   <https://cran.r-project.org/web/packages/portfolioBacktest/vignettes/PortfolioBacktest.html>

<!--# break -->

## Finance, Risk, Timeseries, Optimization functions

-   **`Finance View Cran`**

    -   All finance-related packages on R (CRAN). Amazing.

    -   <https://cran.r-project.org/web/views/Finance.html>

-   **`introcompfinr`**

    -   [Link
        Introcompfin](https://bookdown.org/compfinezbook/introcompfinr/Determining-Mean-Variance-Effici.html)

-   **`Rmetrics`** (*Framwork, several packages published*)

    -   PDF-book Portfolio Optim:
        <https://www.rmetrics.org/downloads/9783906041018-fPortfolio.pdf>

    -   Rmetrics fPortfolio vignette(GOOD) part 1 & 2:

        -   P1:
            <https://miltonfmr.com/the-complete-guide-to-portfolio-optimization-in-r-part1/#rollstats>
        -   P2:
            <https://miltonfmr.com/the-complete-guide-to-portfolio-optimization-in-r-part2/>

-   **`tidyquant`** (*Finance*)

    -   link: <https://business-science.github.io/tidyquant/>

<!--# break -->

-   **`BLCOP`** (*Black-Litterman model framework*)

    -   link:
        <https://cran.r-project.org/web/packages/BLCOP/vignettes/BLCOP.html>
    -   install: install.packages("BLCOP",
        repos="<http://R-Forge.R-project.org>")
    -   Found via: <https://r-forge.r-project.org/R/?group_id=156>

-   **`QRMtools`**(*general functions finance*)

    -   I found this on youtube sometime when I studied for my exams. I
        have stored the link ever since, very nice and powerful tools
        and knowledge sharing!
    -   <https://cran.r-project.org/web/packages/qrmtools/vignettes/geometric_risk_measures.html>
    -   <https://www.qrmtutorial.org/r-code?fbclid=IwAR1Qnkkq9d_Gt28-ptQmTmLpbIcGNwMudKxYyKFONKgkfWoa8X8p1HIXLg4>
        <!--# break -->

-   **`FRAPO`**

    -   <https://www.pfaffikus.de/books/jwex2/>
    -   <https://www.pfaffikus.de/>

<!--# break -->

## Blogroll: Finance & R-code

**BLOG-ROLL**

-   **`The R Trader`**

link: <https://www.thertrader.com/>

-   **`r-bloggers`**

link: <https://www.r-bloggers.com/>

-   **`datacamp.`**

link: <https://learn.datacamp.com/>

-   

    <!--# break -->

#### [**Script som laster inn alle pakker.**]{.ul}

```{r, eval=FALSE, inlcude=FALSE}
# Pakker jeg bruker 
##########################################
# List of useful epidemiology R packages #
##########################################
# This script uses the p_load() function from pacman R package, 
# which installs if package is absent, and loads for use if already installed
# Ensures the package "pacman" is installed
if (!require("pacman")) install.packages("pacman")
# Packages available from CRAN
##############################
pacman::p_load(
  
  # learning R
  ############
  learnr,   # interactive tutorials in RStudio Tutorial pane
  swirl,    # interactive tutorials in R console
  
  # project and file management
  #############################
  here,     # file paths relative to R project root folder
  rio,      # import/export of many types of data
  openxlsx, # import/export of multi-sheet Excel workbooks 
  
  # package install and management
  ################################
  pacman,   # package install/load
  renv,     # managing versions of packages when working in collaborative groups
  remotes,  # install from github
  
  # General data management
  #########################
  tidyverse,    # includes many packages for tidy data wrangling and presentation
  #dplyr,      # data management
  #tidyr,      # data management
  #ggplot2,    # data visualization
  #stringr,    # work with strings and characters
  #forcats,    # work with factors 
  #lubridate,  # work with dates
  #purrr       # iteration and working with lists
  linelist,     # cleaning linelists
  naniar,       # assessing missing data
  
  # statistics  
  ############
  janitor,      # tables and data cleaning
  gtsummary,    # making descriptive and statistical tables
  rstatix,      # quickly run statistical tests and summaries
  broom,        # tidy up results from regressions
  lmtest,       # likelihood-ratio tests
  easystats,
  # parameters, # alternative to tidy up results from regressions
  # see,        # alternative to visualise forest plots 
  
  # epidemic modeling
  ###################
  epicontacts,  # Analysing transmission networks
  EpiNow2,      # Rt estimation
  EpiEstim,     # Rt estimation
  projections,  # Incidence projections
  incidence2,   # Make epicurves and handle incidence data
  i2extras,     # Extra functions for the incidence2 package
  epitrix,      # Useful epi functions
  distcrete,    # Discrete delay distributions
  
  
  # plots - general
  #################
  #ggplot2,         # included in tidyverse
  cowplot,          # combining plots  
  # patchwork,      # combining plots (alternative)     
  RColorBrewer,     # color scales
  ggnewscale,       # to add additional layers of color schemes
  
  
  # plots - specific types
  ########################
  DiagrammeR,       # diagrams using DOT language
  incidence2,       # epidemic curves
  gghighlight,      # highlight a subset
  ggrepel,          # smart labels
  plotly,           # interactive graphics
  gganimate,        # animated graphics 
  
  
  # gis
  ######
  sf,               # to manage spatial data using a Simple Feature format
  tmap,             # to produce simple maps, works for both interactive and static maps
  OpenStreetMap,    # to add OSM basemap in ggplot map
  spdep,            # spatial statistics 
  
  # routine reports
  #################
  rmarkdown,        # produce PDFs, Word Documents, Powerpoints, and HTML files
  reportfactory,    # auto-organization of R Markdown outputs
  officer,          # powerpoints
  
  # dashboards
  ############
  flexdashboard,    # convert an R Markdown script into a dashboard
  shiny,            # interactive web apps
  
  # tables for presentation
  #########################
  knitr,            # R Markdown report generation and html tables
  flextable,        # HTML tables
  #DT,              # HTML tables (alternative)
  #gt,              # HTML tables (alternative)
  #huxtable,        # HTML tables (alternative) 
  
  # phylogenetics
  ###############
  ggtree,           # visualization and annotation of trees
  ape,              # analysis of phylogenetics and evolution
  treeio            # to visualize phylogenetic files
  
)
```


